name: Copilot Setup Steps

on: push

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    uses: dryvist/.github/.github/workflows/_copilot-setup-steps.yml@10af73f872e043e91ff6327d0ef2548881f61298 # v1.11.2
